# Generated by Django 5.1.5 on 2025-01-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('BLOCK DEL 10', 'BLOCK DEL 10'), ('BLOCK DEL 13', 'BLOCK DEL 13'), ('BLOCK DEL 15', 'BLOCK DEL 15'), ('BLOCK DEL 20', 'BLOCK DEL 20')], max_length=15)),
                ('precioDeVenta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precioDeCosto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fechaDeElaboracion', models.DateField()),
                ('cantidadDisponible', models.PositiveIntegerField()),
                ('cantidadMinRequerida', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Materiales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('unidadDeMedida', models.CharField(choices=[('Kg', 'Kilogramos'), ('g', 'Gramos'), ('palet', 'Palet'), ('l', 'Litros'), ('m3', 'Metro cúbico'), ('bolsa', 'Bolsa'), ('u', 'Unidad')], max_length=15)),
                ('precioDeCosto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidadDisponible', models.PositiveIntegerField()),
                ('cantidadMinRequerida', models.PositiveIntegerField()),
            ],
        ),
    ]
